const { response } = require('express');
//const {pool} = require('../database.conecction/pg.conecction'); asi se importa una clase
const {pool} = require('../../PostgresConecction/PgConecction');

const getAgreement = async (req,res)=>{
    const response = await pool.query('	select * from public."Agreement";');
    res.status(200).json(response.rows);
}
const createAgreement = async (req,res)=>{
    const {pk_id_num, id_fun_boss,name_fun,classs,department,post,adress,year_ev,name_boss,name_period,first_date,date_eva_first,final_date,date_eva_final,stim,objective1,objective2,objective3,objective4,objective5,objective6,objective7,objective8,objective9,objective10,indicator1,indicator2,indicator3,indicator4,indicator5,indicator6,indicator7,indicator8,indicator9,indicator10,product1,product2,product3,product4,product5,product6,product7,product8,product9,product10,percentage1,percentage2,percentage3,percentage4,percentage5,percentage6,percentage7,percentage8,percentage9,percentage10,agreeddate1,agreeddate2,agreeddate3,agreeddate4,agreeddate5,agreeddate6,agreeddate7,agreeddate8,agreeddate9,agreeddate10,followdate1,followdate2,followdate3,followdate4,followdate5,followdate6,followdate7,followdate8,followdate9,followdate10,observations1,observations2,observations3,observations4,observations5,observations6,observations7,observations8,observations9,observations10} = req.body;
    const response = await pool.query('INSERT INTO public."Agreement"(pk_id_num, id_fun_boss,name_fun,classs,department,post,adress,year_ev,name_boss,name_period,first_date,date_eva_first,final_date,date_eva_final,stim,objective1,objective2,objective3,objective4,objective5,objective6,objective7,objective8,objective9,objective10,indicator1,indicator2,indicator3,indicator4,indicator5,indicator6,indicator7,indicator8,indicator9,indicator10,product1,product2,product3,product4,product5,product6,product7,product8,product9,product10,percentage1,percentage2,percentage3,percentage4,percentage5,percentage6,percentage7,percentage8,percentage9,percentage10,agreeddate1,agreeddate2,agreeddate3,agreeddate4,agreeddate5,agreeddate6,agreeddate7,agreeddate8,agreeddate9,agreeddate10,followdate1,followdate2,followdate3,followdate4,followdate5,followdate6,followdate7,followdate8,followdate9,followdate10,observations1,observations2,observations3,observations4,observations5,observations6,observations7,observations8,observations9,observations10) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35,$36,$37,$38,$39,$40,$41,$42,$43,$44,$45,$46,$47,$48,$49,$50,$51,$52,$53,$54,$55,$56,$57,$58,$59,$60,$61,$62,$63,$64,$65,$66,$67,$68,$69,$70,$71,$72,$73,$74,$75,$76,$77,$78,$79,$80,$81,$82,$83,$84,$85)',[pk_id_num, id_fun_boss,name_fun,classs,department,post,adress,year_ev,name_boss,name_period,first_date,date_eva_first,final_date,date_eva_final,stim,objective1,objective2,objective3,objective4,objective5,objective6,objective7,objective8,objective9,objective10,indicator1,indicator2,indicator3,indicator4,indicator5,indicator6,indicator7,indicator8,indicator9,indicator10,product1,product2,product3,product4,product5,product6,product7,product8,product9,product10,percentage1,percentage2,percentage3,percentage4,percentage5,percentage6,percentage7,percentage8,percentage9,percentage10,agreeddate1,agreeddate2,agreeddate3,agreeddate4,agreeddate5,agreeddate6,agreeddate7,agreeddate8,agreeddate9,agreeddate10,followdate1,followdate2,followdate3,followdate4,followdate5,followdate6,followdate7,followdate8,followdate9,followdate10,observations1,observations2,observations3,observations4,observations5,observations6,observations7,observations8,observations9,observations10]);
    
    res.json({
        message: 'Agreement added Succesfully',
        body:{
            agreement:{pk_id_num, id_fun_boss,name_fun,classs,department,post,adress,year_ev,name_boss,name_period,first_date,date_eva_first,final_date,date_eva_final,stim,objective1,objective2,objective3,objective4,objective5,objective6,objective7,objective8,objective9,objective10,indicator1,indicator2,indicator3,indicator4,indicator5,indicator6,indicator7,indicator8,indicator9,indicator10,product1,product2,product3,product4,product5,product6,product7,product8,product9,product10,percentage1,percentage2,percentage3,percentage4,percentage5,percentage6,percentage7,percentage8,percentage9,percentage10,agreeddate1,agreeddate2,agreeddate3,agreeddate4,agreeddate5,agreeddate6,agreeddate7,agreeddate8,agreeddate9,agreeddate10,followdate1,followdate2,followdate3,followdate4,followdate5,followdate6,followdate7,followdate8,followdate9,followdate10,observations1,observations2,observations3,observations4,observations5,observations6,observations7,observations8,observations9,observations10}
        }
    })
};


module.exports = {
    getAgreement,
    createAgreement
}